travis:
  secure:
    BINSTAR_TOKEN: Z/Qdr3WPcDNEuY97pWPSgOMJj1WDABw1NtUO8eKjaZTofs5SjZL59Ofh5pqSO/HYlE7ICtX6YIPIu8qUxTGdAqV8ZmoM7xudOkQ7xcKapzodcdk2wWD6qNgg5P/GZqeSoCoXTQ/SJDaKkf7M+kRhlozy6DHGPdyfnBfgUeI8gm3FadpiS2bG4y6KKhIo3rc/lSrlAffIq69uJRXVNowY5+rjzCZtRMSBw5OQdt07X3YzAWcn/Dqet2sZ3WqcSjKl6gw91Acd8/5+dccWifxfjb4vnJLnbSJ3dHqE3kqtCVImABb5Vi83G986GEh8twEkLZ05qb+s37+rSdyg6IH8hjGuVTJEeMXBGvT/MLFaroXI6NokhwCvz+ky+8xO6JDZxLgCCT2diTMtvy3LrEy+/DbnGwsHzmoitfNjFmiW8quSA099zqnNd3L3/ZyQ3823PT2fDiNiyP4lgWNbUftGgp5PMQZf8+Bi2BB6vt8YKB9qYeTLG7sQwrt791rk0xp9YvsgX1LWWHB4Z4MLUbgaF8eC2xzfqeQHJxpUwy++Z7t6eQWgaX+QjW21AeCmraalFEe8qNPk5DVivIW6jFBso70zrRyTi0HI/hobVI3jnO8wrTEf28NjsmvmAH2PvbJyhZVWfnKAMpXIJ+wiiO8Q8ICJmylMUBqcZmhZBBtpoS0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
